### ISSUE TITLE
User Not Limited to 1-10 Scale

### ISSUE THREAD

**Issue by duncanchadly** [christyroney/Roney_CSCI2270_FinalProject-#5]
Entering values larger than 10 or lower than 1 are allowed to the user when asked to enter rankings on 1-10 scales. Ratings made in this way don't display when options 6-9 are called.

**Comment by purpledonut** [comment]
They then don't display when options 6-9 are called.

**Comment by christyroney** [comment]
Thank you! I added a function for checking if a ranking is valid and used that in my driver valid for the addRankings case.
